
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

from my_functions import comparar, select_file


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\WILLIAM\Downloads\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("735x650")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 650,
    width = 735,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    735.0,
    518.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    29.0,
    28.0,
    707.0,
    631.0,
    fill="#3E3F5B",
    outline="")

canvas.create_rectangle(
    585.0,
    10.0,
    722.0,
    123.0,
    fill="#ACD3A8",
    outline="")

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    647.0,
    66.0,
    image=image_image_1
)

canvas.create_rectangle(
    59.0,
    14.0,
    399.0,
    61.0,
    fill="#ABD2A7",
    outline="")

canvas.create_text(
    67.0,
    22.0,
    anchor="nw",
    text="Localizador de Diferenças",
    fill="#1E1E1E",
    font=("Inter Bold", 25 * -1)
)

canvas.create_text(
    67.0,
    82.0,
    anchor="nw",
    text="Selecione o arquivo 1",
    fill="#FFFFFF",
    font=("Inter Bold", 25 * -1)
)

canvas.create_rectangle(
    67.0,
    123.0,
    312.0,
    158.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    276.0,
    123.0,
    312.0,
    157.0,
    fill="#D9D9D9",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: select_file(file1),
    relief="flat"
)
button_1.place(
    x=275.9999871850014,
    y=125.99999288118602,
    width=33.308739937672534,
    height=28.369651283853045
)
file1 = Entry(
    window,
    bg="#FFFFFF",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
file1.place(x=69, y=123, width=200, height=30)
file1.insert(0, "...")

canvas.create_text(
    67.0,
    169.0,
    anchor="nw",
    text="Selecione o arquivo 2",
    fill="#FFFFFF",
    font=("Inter Bold", 25 * -1)
)

canvas.create_rectangle(
    67.0,
    210.0,
    312.0,
    245.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    276.0,
    210.0,
    312.0,
    244.0,
    fill="#D9D9D9",
    outline="")

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: select_file(file2),
    relief="flat"
)
button_2.place(
    x=275.9999871850014,
    y=212.99999288118602,
    width=33.308739937672534,
    height=28.369651283853045
)
file2 = Entry(
    window,
    bg="#FFFFFF",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
file2.place(x=69, y=210, width=200, height=30)
file2.insert(0, "...")

canvas.create_text(
    74.0,
    271.0,
    anchor="nw",
    text="Diferenças",
    fill="#ACD3A8",
    font=("Inter Bold", 30 * -1)
)

canvas.create_rectangle(
    69.0,
    325.0,
    683.0,
    615.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    69.0,
    325.0,
    683.0,
    354.0,
    fill="#80C18A",
    outline="")

canvas.create_text(
    443.0,
    328.0,
    anchor="nw",
    text="Colunas",
    fill="#000000",
    font=("Inter Bold", 20 * -1)
)

canvas.create_text(
    589.0,
    328.0,
    anchor="nw",
    text="Linhas",
    fill="#000000",
    font=("Inter Bold", 20 * -1)
)

canvas.create_text(
    78.0,
    328.0,
    anchor="nw",
    text="Conteudo Arq 1",
    fill="#000000",
    font=("Inter Bold", 20 * -1)
)

canvas.create_text(
    260.0,
    328.0,
    anchor="nw",
    text="Conteudo Arq 2",
    fill="#000000",
    font=("Inter Bold", 20 * -1)
)

canvas.create_rectangle(
    243.49122619628906,
    323.9991149902344,
    244.49122619628912,
    615.0008239746094,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    427.0,
    325.0,
    428.00000000000006,
    616.001708984375,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    557.0,
    325.0,
    558.0000000000001,
    616.001708984375,
    fill="#000000",
    outline="")

# Conteudo_arq1
content_rows = Entry(
    window,
    bg="#D9D9D9",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
content_rows.place(x=83, y=361, width=100, height=30)
content_rows.insert(0, "...")

# Conteudo_arq2
content_rows = Entry(
    window,
    bg="#D9D9D9",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
content_rows.place(x=270, y=361, width=100, height=30)
content_rows.insert(0, "...")

# Coluna de Colunas
columns_rows = Entry(
    window,
    bg="#D9D9D9",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
columns_rows.place(x=441, y=361, width=100, height=30)
columns_rows.insert(0, "...")

# Coluna de Linhas
rows_rows = Entry(
    window,
    bg="#D9D9D9",
    fg="#000000",
    font=("Inter Bold", 15),
    borderwidth=0
)
rows_rows.place(x=570, y=361, width=100, height=30)
rows_rows.insert(0, "...")

button_comparar = Button(
    window,
    text="Comparar Planilhas",
    command=lambda: comparar(file1,file2,content_rows,columns_rows,rows_rows),
    bg="#4CAF50",
    fg="#FFFFFF",
    font=("Inter Bold", 15),
)
button_comparar.place(x=450, y=200, width=200, height=40)

window.resizable(False, False)
window.mainloop()
